# -*- coding: utf-8 -*-
"""Part 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120LIrDY7E4Rv74QtGQCaO8xlsG3Kqzvd
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile cell1_fixed.py
# import pandas as pd, numpy as np, re
# from sklearn.linear_model import LinearRegression
# from sklearn.preprocessing import PolynomialFeatures
# from sklearn.pipeline import make_pipeline
# 
# stats = pd.read_csv('nba_stats_cleaned.csv')
# sal   = pd.read_csv('NBA Player Salaries_2024-25_1.csv')
# 
# def norm_name(n):
#     if pd.isna(n): return np.nan
#     n = re.sub(r'[.]+','',str(n).strip())
#     return re.sub(r'\s+',' ',n).lower()
# 
# stats['_key'] = stats['Player'].apply(norm_name)
# sal['_key']   = sal['Player'].apply(norm_name)
# 
# sal['Salary_Millions'] = (sal['Salary'].astype(str)
#     .str.replace('$','',regex=False).str.replace(',','',regex=False)
#     .str.strip().pipe(pd.to_numeric,errors='coerce').div(1e6))
# sal = sal[sal['Salary_Millions'].gt(0) & sal['Salary_Millions'].notna()]
# 
# tmap = {'PHO':'PHX','GS':'GSW','NO':'NOP','NY':'NYK','SA':'SAS'}
# for d in [stats,sal]:
#     if 'Team' in d.columns:
#         d['Team'] = d['Team'].astype(str).str.strip().str.upper().map(lambda t: tmap.get(t,t))
# 
# slim = sal[['_key','Team','Salary_Millions']].drop_duplicates(['_key','Team'])
# merged = stats.merge(slim, on=['_key','Team'], how='inner')
# print('Merged P+T:',len(merged))
# if len(merged)<100:
#     slim2 = sal[['_key','Salary_Millions']].sort_values('Salary_Millions',ascending=False).drop_duplicates('_key')
#     merged = stats.merge(slim2, on='_key', how='inner')
#     print('Fallback P-only:',len(merged))
# 
# for c in ['PER','USG%','PTS','AST','TRB','STL','BLK','G','MP']:
#     if c in merged.columns:
#         merged[c] = pd.to_numeric(merged[c],errors='coerce')
# 
# merged = merged.dropna(subset=['PER','USG%','Salary_Millions','G','MP'])
# print('Before filter:',len(merged))
# merged = merged[(merged['G']>=40)&(merged['MP']>=20)&(merged['Salary_Millions']>=0.5)].copy()
# print('After filter (>=40G, >=20MPG, >=$500K):',len(merged))
# 
# X = merged[['Salary_Millions']].values
# y = merged['PER'].values
# model = make_pipeline(PolynomialFeatures(2), LinearRegression())
# model.fit(X,y)
# merged['Expected_PER'] = model.predict(X)
# merged['Efficiency_Surplus'] = (merged['PER'] - merged['Expected_PER']).round(2)
# merged['Surplus_Rank'] = merged['Efficiency_Surplus'].rank(ascending=False,method='min').astype(int)
# merged['PER_Rank'] = merged['PER'].rank(ascending=False,method='min').astype(int)
# merged['Salary_Rank'] = merged['Salary_Millions'].rank(ascending=False,method='min').astype(int)
# merged['PVI'] = (merged['PER']+merged['USG%'])/merged['Salary_Millions']
# 
# def stier(m):
#     if m>=25: return 'Superstar (>=25M)'
#     if m>=15: return 'Star (15-25M)'
#     if m>=5:  return 'Role Player (5-15M)'
#     return 'Minimum/Vet (<5M)'
# def vlabel(s):
#     if s>=4: return 'STEAL'
#     if s>=1.5: return 'Undervalued'
#     if s>=-1.5: return 'Fair Value'
#     if s>=-4: return 'Overpaid'
#     return 'WAY Overpaid'
# 
# merged['Salary_Tier'] = merged['Salary_Millions'].apply(stier)
# merged['Value_Label'] = merged['Efficiency_Surplus'].apply(vlabel)
# merged['Player_display'] = merged['Player']
# merged.to_csv('nba_stats_salaries_merged_with_pvi.csv',index=False)
# print('Saved. Final shape:',merged.shape)
# print('R2 salary->PER:',round(model.score(X,y),3))
# 
# cols = ['Player_display','Team','Pos','G','MP','Salary_Millions','PER','Expected_PER','Efficiency_Surplus','Surplus_Rank','Salary_Tier','Value_Label']
# print('\nTOP 15 STEALS:')
# print(merged.nlargest(15,'Efficiency_Surplus')[cols].to_string(index=False))
# print('\nBOTTOM 15 OVERPAID:')
# print(merged.nsmallest(15,'Efficiency_Surplus')[cols].to_string(index=False))

# Commented out IPython magic to ensure Python compatibility.
# CELL 1B - Run the fixed data pipeline
# %run cell1_fixed.py

import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

df = merged.copy()

TIER_ORDER = ['Superstar (>=25M)', 'Star (15-25M)', 'Role Player (5-15M)', 'Minimum/Vet (<5M)']
TIER_COLORS = {
    'Superstar (>=25M)': '#e63946',
    'Star (15-25M)': '#f4a261',
    'Role Player (5-15M)': '#2a9d8f',
    'Minimum/Vet (<5M)': '#457b9d'
}
VAL_COLORS = {
    'STEAL': '#006400',
    'Undervalued': '#2a9d8f',
    'Fair Value': '#adb5bd',
    'Overpaid': '#f4a261',
    'WAY Overpaid': '#e63946'
}

df["Salary_Tier"] = pd.Categorical(df["Salary_Tier"], categories=TIER_ORDER, ordered=True)

fig1 = px.scatter(
    df,
    x="Salary_Millions",
    y="PER",
    size="USG%",
    color="Salary_Tier",
    hover_name="Player_display",
    hover_data=["Team", "Pos", "G", "MP", "Expected_PER", "Efficiency_Surplus", "Value_Label"],
    color_discrete_map=TIER_COLORS,
    title="Salary vs PER (Bubble Size = Usage Rate)"
)
fig1.update_layout(template="plotly_white")

fig2 = px.scatter(
    df,
    x="Salary_Millions",
    y="Efficiency_Surplus",
    size="USG%",
    color="Value_Label",
    hover_name="Player_display",
    hover_data=["Team", "Pos", "PER", "Expected_PER", "Salary_Tier"],
    color_discrete_map=VAL_COLORS,
    title="Salary vs Efficiency Surplus"
)
fig2.add_hline(y=0, line_dash="dash", line_color="black")
fig2.update_layout(template="plotly_white")

top20 = df.sort_values("Efficiency_Surplus", ascending=False).head(20).copy()
fig3 = go.Figure(data=[go.Table(
    header=dict(
        values=["Rank", "Player", "Team", "Pos", "Salary ($M)", "PER", "Expected PER", "Surplus", "Tier", "Label"],
        fill_color="#1d3557",
        font=dict(color="white", size=12),
        align="left"
    ),
    cells=dict(
        values=[
            top20["Surplus_Rank"],
            top20["Player_display"],
            top20["Team"],
            top20["Pos"],
            top20["Salary_Millions"].round(2),
            top20["PER"].round(2),
            top20["Expected_PER"].round(2),
            top20["Efficiency_Surplus"].round(2),
            top20["Salary_Tier"],
            top20["Value_Label"]
        ],
        fill_color="#f8f9fa",
        align="left"
    )
)])
fig3.update_layout(title="Top 20 Value Players by Efficiency Surplus")

team_surplus = (
    df.groupby("Team", as_index=False)
      .agg(Avg_Surplus=("Efficiency_Surplus", "mean"),
           Avg_Salary_M=("Salary_Millions", "mean"),
           Avg_PER=("PER", "mean"),
           Players=("Player_display", "count"))
      .sort_values("Avg_Surplus", ascending=False)
)

fig4 = px.bar(
    team_surplus,
    x="Team",
    y="Avg_Surplus",
    color="Avg_Surplus",
    color_continuous_scale="RdYlGn",
    hover_data=["Avg_Salary_M", "Avg_PER", "Players"],
    title="Team Average Efficiency Surplus"
)
fig4.update_layout(template="plotly_white")

team_payroll = (
    df.groupby("Team", as_index=False)
      .agg(Total_Payroll_M=("Salary_Millions", "sum"),
           Avg_PER=("PER", "mean"),
           Avg_Surplus=("Efficiency_Surplus", "mean"),
           Players=("Player_display", "count"))
)

fig5 = px.scatter(
    team_payroll,
    x="Total_Payroll_M",
    y="Avg_PER",
    size="Players",
    color="Avg_Surplus",
    hover_name="Team",
    hover_data=["Players"],
    color_continuous_scale="RdYlGn",
    title="Team Payroll vs Average PER"
)
fig5.update_layout(template="plotly_white")

fig1.show()
fig2.show()
fig3.show()
fig4.show()
fig5.show()



from plotly.io import to_html

dashboard_html = f"""
<html>
<head>
    <title>NBA Salary Efficiency Dashboard</title>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 20px;
            background: #f8f9fa;
            color: #222;
        }}
        h1, h2 {{
            color: #1d3557;
        }}
        .chart {{
            margin-bottom: 50px;
            padding: 20px;
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        .summary {{
            background: white;
            padding: 20px;
            border-radius: 12px;
            margin-bottom: 30px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
    </style>
</head>
<body>
    <h1>NBA Salary Efficiency Dashboard (2024-25)</h1>

    <div class="summary">
        <h2>Project Summary</h2>
        <p>This dashboard merges NBA player performance and salary data to evaluate contract value.</p>
        <p>Players were filtered to rotation-level contributors: at least 40 games, at least 20 MPG, and salary at least $0.5M.</p>
        <p>Value is measured using <b>Efficiency Surplus</b> = Actual PER - Expected PER, where Expected PER is predicted from salary using a polynomial regression model.</p>
    </div>

    <div class="chart">{to_html(fig1, full_html=False, include_plotlyjs='cdn')}</div>
    <div class="chart">{to_html(fig2, full_html=False, include_plotlyjs=False)}</div>
    <div class="chart">{to_html(fig3, full_html=False, include_plotlyjs=False)}</div>
    <div class="chart">{to_html(fig4, full_html=False, include_plotlyjs=False)}</div>
    <div class="chart">{to_html(fig5, full_html=False, include_plotlyjs=False)}</div>
</body>
</html>
"""

with open("nba_salary_dashboard.html", "w", encoding="utf-8") as f:
    f.write(dashboard_html)

print("Dashboard saved: nba_salary_dashboard.html")

team_summary = (
    merged.groupby("Team", as_index=False)
          .agg(
              Avg_Salary_M=("Salary_Millions", "mean"),
              Avg_PER=("PER", "mean"),
              Avg_PVI=("PVI", "mean"),
              Avg_Surplus=("Efficiency_Surplus", "mean"),
              Player_Count=("Player_display", "count")
          )
          .sort_values("Avg_Surplus", ascending=False)
)

best_team = team_summary.iloc[0]
worst_team = team_summary.iloc[-1]
best_player = merged.loc[merged["Efficiency_Surplus"].idxmax()]
worst_player = merged.loc[merged["Efficiency_Surplus"].idxmin()]

print("\n=========== FINAL FILTERED DATASET SUMMARY ===========")
print(f"Total players analyzed: {len(merged)}")
print(f"Salary range: ${merged['Salary_Millions'].min():.2f}M – ${merged['Salary_Millions'].max():.2f}M")
print(f"PER range: {merged['PER'].min():.1f} – {merged['PER'].max():.1f}")
print(f"Efficiency Surplus range: {merged['Efficiency_Surplus'].min():.2f} – {merged['Efficiency_Surplus'].max():.2f}")
print(f"Median Salary: ${merged['Salary_Millions'].median():.1f}M")
print(f"Median PER: {merged['PER'].median():.1f}")
print()
print(f"Top value player: {best_player['Player_display']} ({best_player['Team']}) Surplus={best_player['Efficiency_Surplus']:.2f}")
print(f"Most overpaid player: {worst_player['Player_display']} ({worst_player['Team']}) Surplus={worst_player['Efficiency_Surplus']:.2f}")
print(f"Most efficient team: {best_team['Team']} Avg Surplus={best_team['Avg_Surplus']:.2f}")
print(f"Least efficient team: {worst_team['Team']} Avg Surplus={worst_team['Avg_Surplus']:.2f}")

display(team_summary.head(10))